export const CURSOS_UFMG = [
  "Administração (Bacharelado) — Belo Horizonte",
  "Administração (Bacharelado) — Montes Claros",
  "Agronomia (Bacharelado)",
  "Antropologia (Bacharelado)",
  "Aquacultura (Bacharelado)",
  "Arqueologia (Bacharelado)",
  "Arquitetura e Urbanismo (Bacharelado)",
  "Arquivologia (Bacharelado)",
  "Artes Visuais (Bacharelado)",
  "Artes Visuais (Licenciatura)",
  "Biblioteconomia (Bacharelado)",
  "Biomedicina (Bacharelado)",
  "Ciência da Computação (Bacharelado)",
  "Ciência de Dados (Bacharelado)",
  "Ciências Atuariais (Bacharelado)",
  "Ciências Biológicas (Bacharelado)",
  "Ciências Biológicas (Licenciatura)",
  "Ciências Contábeis (Bacharelado)",
  "Ciências da Natureza (Licenciatura)",
  "Ciências do Estado (Bacharelado)",
  "Ciências Econômicas (Bacharelado)",
  "Ciências Sociais (Bacharelado)",
  "Ciências Sociais (Licenciatura)",
  "Ciências Socioambientais (Bacharelado)",
  "Cinema de Animação e Artes Digitais (Bacharelado)",
  "Conservação e Restauração de Bens Culturais Móveis (Bacharelado)",
  "Controladoria e Finanças (Bacharelado)",
  "Dança (Licenciatura)",
  "Design (Bacharelado)",
  "Design de Moda (Bacharelado)",
  "Direito (Bacharelado)",
  "Educação do Campo (Licenciatura)",
  "Educação Física (Bacharelado)",
  "Educação Física (Licenciatura)",
  "Enfermagem (Bacharelado)",
  "Engenharia Aeroespacial (Bacharelado)",
  "Engenharia Agrícola e Ambiental (Bacharelado)",
  "Engenharia Ambiental (Bacharelado)",
  "Engenharia Civil (Bacharelado)",
  "Engenharia de Alimentos (Bacharelado)",
  "Engenharia de Computação (Bacharelado)",
  "Engenharia de Controle e Automação (Bacharelado)",
  "Engenharia de Materiais (Bacharelado)",
  "Engenharia de Minas (Bacharelado)",
  "Engenharia de Produção (Bacharelado)",
  "Engenharia de Sistemas (Bacharelado)",
  "Engenharia Elétrica (Bacharelado)",
  "Engenharia Florestal (Bacharelado)",
  "Engenharia Mecânica (Bacharelado)",
  "Engenharia Metalúrgica (Bacharelado)",
  "Engenharia Química (Bacharelado)",
  "Estatística (Bacharelado)",
  "Farmácia (Bacharelado)",
  "Filosofia (Bacharelado)",
  "Filosofia (Licenciatura)",
  "Física (Bacharelado)",
  "Física (Licenciatura)",
  "Fisioterapia (Bacharelado)",
  "Fonoaudiologia (Bacharelado)",
  "Formação Intercultural para Educadores Indígenas (Licenciatura)",
  "Geografia (Bacharelado)",
  "Geografia (Licenciatura)",
  "Geologia (Bacharelado)",
  "Gestão de Serviços de Saúde (Bacharelado)",
  "Gestão Pública (Bacharelado)",
  "História (Bacharelado)",
  "História (Licenciatura)",
  "Jornalismo (Bacharelado)",
  "Letras (Bacharelado)",
  "Letras (Licenciatura)",
  "Letras-Libras (Licenciatura)",
  "Matemática (Bacharelado)",
  "Matemática (Licenciatura) — Belo Horizonte",
  "Matemática (Licenciatura) — Montes Claros",
  "Matemática Computacional (Bacharelado)",
  "Medicina (Bacharelado)",
  "Medicina Veterinária (Bacharelado)",
  "Museologia (Bacharelado)",
  "Música (Bacharelado)",
  "Música (Licenciatura)",
  "Nutrição (Bacharelado)",
  "Odontologia (Bacharelado)",
  "Pedagogia (Licenciatura)",
  "Psicologia (Bacharelado)",
  "Publicidade e Propaganda (Bacharelado)",
  "Química (Bacharelado)",
  "Química (Licenciatura)",
  "Química Tecnológica (Bacharelado)",
  "Radiologia (Superior de Tecnologia)",
  "Relações Econômicas Internacionais (Bacharelado)",
  "Relações Públicas (Bacharelado)",
  "Sistemas de Informação (Bacharelado)",
  "Teatro (Bacharelado)",
  "Teatro (Licenciatura)",
  "Terapia Ocupacional (Bacharelado)",
  "Turismo (Bacharelado)",
  "Zootecnia (Bacharelado)",
] as const;
