export const INSTITUICOES_FEDERAIS = [
  "Universidade da Integração Internacional da Lusofonia Afro-Brasileira",
  "Universidade de Brasília",
  "Universidade Federal da Bahia",
  "Universidade Federal da Fronteira Sul",
  "Universidade Federal da Integração Latino-Americana",
  "Universidade Federal da Paraíba",
  "Universidade Federal de Alagoas",
  "Universidade Federal de Alfenas",
  "Universidade Federal de Campina Grande",
  "Universidade Federal de Catalão",
  "Universidade Federal de Ciência e Inovação de Minas Gerais",
  "Universidade Federal de Ciência e Inovação do Rio de Janeiro",
  "Universidade Federal de Ciências da Saúde de Porto Alegre",
  "Universidade Federal de Goiás",
  "Universidade Federal de Itajubá",
  "Universidade Federal de Jataí",
  "Universidade Federal de Juiz de Fora",
  "Universidade Federal de Lavras",
  "Universidade Federal de Mato Grosso",
  "Universidade Federal de Mato Grosso do Sul",
  "Universidade Federal de Minas Gerais",
  "Universidade Federal de Ouro Preto",
  "Universidade Federal de Pelotas",
  "Universidade Federal de Pernambuco",
  "Universidade Federal de Rondonópolis",
  "Universidade Federal de Rondônia",
  "Universidade Federal de Roraima",
  "Universidade Federal de Santa Catarina",
  "Universidade Federal de Santa Maria",
  "Universidade Federal de São Carlos",
  "Universidade Federal de São João del-Rei",
  "Universidade Federal de São Paulo",
  "Universidade Federal de Sergipe",
  "Universidade Federal de Uberlândia",
  "Universidade Federal de Viçosa",
  "Universidade Federal do ABC",
  "Universidade Federal do Acre",
  "Universidade Federal do Agreste de Pernambuco",
  "Universidade Federal do Amapá",
  "Universidade Federal do Amazonas",
  "Universidade Federal do Cariri",
  "Universidade Federal do Ceará",
  "Universidade Federal do Delta do Parnaíba",
  "Universidade Federal do Espírito Santo",
  "Universidade Federal do Estado do Rio de Janeiro",
  "Universidade Federal do Maranhão",
  "Universidade Federal do Norte do Tocantins",
  "Universidade Federal do Oeste da Bahia",
  "Universidade Federal do Oeste do Pará",
  "Universidade Federal do Pampa",
  "Universidade Federal do Pará",
  "Universidade Federal do Paraná",
  "Universidade Federal do Piauí",
  "Universidade Federal do Recôncavo da Bahia",
  "Universidade Federal do Rio de Janeiro",
  "Universidade Federal do Rio Grande",
  "Universidade Federal do Rio Grande do Norte",
  "Universidade Federal do Rio Grande do Sul",
  "Universidade Federal do Sul da Bahia",
  "Universidade Federal do Sul e Sudeste do Pará",
  "Universidade Federal do Tocantins",
  "Universidade Federal do Triângulo Mineiro",
  "Universidade Federal do Vale do São Francisco",
  "Universidade Federal dos Vales do Jequitinhonha e Mucuri",
  "Universidade Federal Fluminense",
  "Universidade Federal Rural da Amazônia",
  "Universidade Federal Rural de Pernambuco",
  "Universidade Federal Rural do Rio de Janeiro",
  "Universidade Federal Rural do Semi-Árido",
  "Universidade Federal da Grande Dourados",
  "Universidade Tecnológica Federal do Paraná",
] as const;
